package com.startupComp.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class UserStartup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.USER_ID
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.PHONE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.SCHOOL_NAME
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private String schoolName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.PASSWORD
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.PASSWORD_ENCRY
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private String passwordEncry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.HEAD_PIC
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private String headPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.LOGIN_NUM
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private String loginNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.LOGIN_TYPE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private String loginType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.LOGIN_DATE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date loginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column startup_user.READY
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	private String ready;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.USER_ID
	 * @return  the value of startup_user.USER_ID
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.USER_ID
	 * @param userId  the value for startup_user.USER_ID
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.PHONE
	 * @return  the value of startup_user.PHONE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.PHONE
	 * @param phone  the value for startup_user.PHONE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.SCHOOL_NAME
	 * @return  the value of startup_user.SCHOOL_NAME
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public String getSchoolName() {
		return schoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.SCHOOL_NAME
	 * @param schoolName  the value for startup_user.SCHOOL_NAME
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.PASSWORD
	 * @return  the value of startup_user.PASSWORD
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.PASSWORD
	 * @param password  the value for startup_user.PASSWORD
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.PASSWORD_ENCRY
	 * @return  the value of startup_user.PASSWORD_ENCRY
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public String getPasswordEncry() {
		return passwordEncry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.PASSWORD_ENCRY
	 * @param passwordEncry  the value for startup_user.PASSWORD_ENCRY
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setPasswordEncry(String passwordEncry) {
		this.passwordEncry = passwordEncry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.HEAD_PIC
	 * @return  the value of startup_user.HEAD_PIC
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public String getHeadPic() {
		return headPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.HEAD_PIC
	 * @param headPic  the value for startup_user.HEAD_PIC
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setHeadPic(String headPic) {
		this.headPic = headPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.LOGIN_NUM
	 * @return  the value of startup_user.LOGIN_NUM
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public String getLoginNum() {
		return loginNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.LOGIN_NUM
	 * @param loginNum  the value for startup_user.LOGIN_NUM
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setLoginNum(String loginNum) {
		this.loginNum = loginNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.LOGIN_TYPE
	 * @return  the value of startup_user.LOGIN_TYPE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public String getLoginType() {
		return loginType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.LOGIN_TYPE
	 * @param loginType  the value for startup_user.LOGIN_TYPE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setLoginType(String loginType) {
		this.loginType = loginType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.LOGIN_DATE
	 * @return  the value of startup_user.LOGIN_DATE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public Date getLoginDate() {
		return loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.LOGIN_DATE
	 * @param loginDate  the value for startup_user.LOGIN_DATE
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column startup_user.READY
	 * @return  the value of startup_user.READY
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public String getReady() {
		return ready;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column startup_user.READY
	 * @param ready  the value for startup_user.READY
	 * @mbggenerated  Wed May 11 10:39:22 CST 2016
	 */
	public void setReady(String ready) {
		this.ready = ready;
	}
}