package com.startupComp.model;

import java.util.Date;

public class UserStartup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.USER_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.MOBILE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.USER_TYPE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.PASSWORD
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.REG_TIME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.STATUS
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.LAST_LOGIN_TIME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.LAST_LOGIN_IP
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.BUSINESS_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.SCHOOL_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.EMAIL
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.HEAD_PIC
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String headPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.DORMBUILDING_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String dormbuildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.DORM_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String dormId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.BUSINESS_TYPE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.SOURCE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.SCHEDULE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String schedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.REFEREE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String referee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.SCHOOL_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.OTHER_DEVICE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String otherDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.WX_IMAGE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String wxImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.PROVINCE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.PROVINCE_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.CITY
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startupcomp_user.CITY_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.USER_ID
     *
     * @return the value of startupcomp_user.USER_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.USER_ID
     *
     * @param userId the value for startupcomp_user.USER_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.MOBILE
     *
     * @return the value of startupcomp_user.MOBILE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.MOBILE
     *
     * @param mobile the value for startupcomp_user.MOBILE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.USER_TYPE
     *
     * @return the value of startupcomp_user.USER_TYPE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.USER_TYPE
     *
     * @param userType the value for startupcomp_user.USER_TYPE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.PASSWORD
     *
     * @return the value of startupcomp_user.PASSWORD
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.PASSWORD
     *
     * @param password the value for startupcomp_user.PASSWORD
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.REG_TIME
     *
     * @return the value of startupcomp_user.REG_TIME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.REG_TIME
     *
     * @param regTime the value for startupcomp_user.REG_TIME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.STATUS
     *
     * @return the value of startupcomp_user.STATUS
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.STATUS
     *
     * @param status the value for startupcomp_user.STATUS
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.LAST_LOGIN_TIME
     *
     * @return the value of startupcomp_user.LAST_LOGIN_TIME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for startupcomp_user.LAST_LOGIN_TIME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.LAST_LOGIN_IP
     *
     * @return the value of startupcomp_user.LAST_LOGIN_IP
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.LAST_LOGIN_IP
     *
     * @param lastLoginIp the value for startupcomp_user.LAST_LOGIN_IP
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.BUSINESS_NAME
     *
     * @return the value of startupcomp_user.BUSINESS_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.BUSINESS_NAME
     *
     * @param businessName the value for startupcomp_user.BUSINESS_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.SCHOOL_NAME
     *
     * @return the value of startupcomp_user.SCHOOL_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.SCHOOL_NAME
     *
     * @param schoolName the value for startupcomp_user.SCHOOL_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.EMAIL
     *
     * @return the value of startupcomp_user.EMAIL
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.EMAIL
     *
     * @param email the value for startupcomp_user.EMAIL
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.HEAD_PIC
     *
     * @return the value of startupcomp_user.HEAD_PIC
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.HEAD_PIC
     *
     * @param headPic the value for startupcomp_user.HEAD_PIC
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.DORMBUILDING_ID
     *
     * @return the value of startupcomp_user.DORMBUILDING_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getDormbuildingId() {
        return dormbuildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.DORMBUILDING_ID
     *
     * @param dormbuildingId the value for startupcomp_user.DORMBUILDING_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setDormbuildingId(String dormbuildingId) {
        this.dormbuildingId = dormbuildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.DORM_ID
     *
     * @return the value of startupcomp_user.DORM_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getDormId() {
        return dormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.DORM_ID
     *
     * @param dormId the value for startupcomp_user.DORM_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setDormId(String dormId) {
        this.dormId = dormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.BUSINESS_TYPE
     *
     * @return the value of startupcomp_user.BUSINESS_TYPE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.BUSINESS_TYPE
     *
     * @param businessType the value for startupcomp_user.BUSINESS_TYPE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.SOURCE
     *
     * @return the value of startupcomp_user.SOURCE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.SOURCE
     *
     * @param source the value for startupcomp_user.SOURCE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.SCHEDULE
     *
     * @return the value of startupcomp_user.SCHEDULE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.SCHEDULE
     *
     * @param schedule the value for startupcomp_user.SCHEDULE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.REFEREE
     *
     * @return the value of startupcomp_user.REFEREE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getReferee() {
        return referee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.REFEREE
     *
     * @param referee the value for startupcomp_user.REFEREE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setReferee(String referee) {
        this.referee = referee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.SCHOOL_ID
     *
     * @return the value of startupcomp_user.SCHOOL_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.SCHOOL_ID
     *
     * @param schoolId the value for startupcomp_user.SCHOOL_ID
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.OTHER_DEVICE
     *
     * @return the value of startupcomp_user.OTHER_DEVICE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getOtherDevice() {
        return otherDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.OTHER_DEVICE
     *
     * @param otherDevice the value for startupcomp_user.OTHER_DEVICE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setOtherDevice(String otherDevice) {
        this.otherDevice = otherDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.WX_IMAGE
     *
     * @return the value of startupcomp_user.WX_IMAGE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getWxImage() {
        return wxImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.WX_IMAGE
     *
     * @param wxImage the value for startupcomp_user.WX_IMAGE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setWxImage(String wxImage) {
        this.wxImage = wxImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.PROVINCE
     *
     * @return the value of startupcomp_user.PROVINCE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.PROVINCE
     *
     * @param province the value for startupcomp_user.PROVINCE
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.PROVINCE_NAME
     *
     * @return the value of startupcomp_user.PROVINCE_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.PROVINCE_NAME
     *
     * @param provinceName the value for startupcomp_user.PROVINCE_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.CITY
     *
     * @return the value of startupcomp_user.CITY
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.CITY
     *
     * @param city the value for startupcomp_user.CITY
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startupcomp_user.CITY_NAME
     *
     * @return the value of startupcomp_user.CITY_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startupcomp_user.CITY_NAME
     *
     * @param cityName the value for startupcomp_user.CITY_NAME
     *
     * @mbggenerated Fri May 06 12:56:34 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
}