package com.startupComp.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Works {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_ID
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private Integer worksId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_NAME
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_DATE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date worksDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_TYPE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_LIKE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private Integer worksLike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_COLL
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private Integer worksColl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_COMMENT
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_AUTHOR
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_IMG1
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksImg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_IMG2
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksImg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_IMG3
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksImg3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_IMG4
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksImg4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_IMG5
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksImg5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column startup_works.WORKS_CONTENT
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    private String worksContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_ID
     *
     * @return the value of startup_works.WORKS_ID
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public Integer getWorksId() {
        return worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_ID
     *
     * @param worksId the value for startup_works.WORKS_ID
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksId(Integer worksId) {
        this.worksId = worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_NAME
     *
     * @return the value of startup_works.WORKS_NAME
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksName() {
        return worksName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_NAME
     *
     * @param worksName the value for startup_works.WORKS_NAME
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksName(String worksName) {
        this.worksName = worksName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_DATE
     *
     * @return the value of startup_works.WORKS_DATE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public Date getWorksDate() {
        return worksDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_DATE
     *
     * @param worksDate the value for startup_works.WORKS_DATE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksDate(Date worksDate) {
        this.worksDate = worksDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_TYPE
     *
     * @return the value of startup_works.WORKS_TYPE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksType() {
        return worksType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_TYPE
     *
     * @param worksType the value for startup_works.WORKS_TYPE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksType(String worksType) {
        this.worksType = worksType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_LIKE
     *
     * @return the value of startup_works.WORKS_LIKE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public Integer getWorksLike() {
        return worksLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_LIKE
     *
     * @param worksLike the value for startup_works.WORKS_LIKE
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksLike(Integer worksLike) {
        this.worksLike = worksLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_COLL
     *
     * @return the value of startup_works.WORKS_COLL
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public Integer getWorksColl() {
        return worksColl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_COLL
     *
     * @param worksColl the value for startup_works.WORKS_COLL
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksColl(Integer worksColl) {
        this.worksColl = worksColl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_COMMENT
     *
     * @return the value of startup_works.WORKS_COMMENT
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksComment() {
        return worksComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_COMMENT
     *
     * @param worksComment the value for startup_works.WORKS_COMMENT
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksComment(String worksComment) {
        this.worksComment = worksComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_AUTHOR
     *
     * @return the value of startup_works.WORKS_AUTHOR
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksAuthor() {
        return worksAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_AUTHOR
     *
     * @param worksAuthor the value for startup_works.WORKS_AUTHOR
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksAuthor(String worksAuthor) {
        this.worksAuthor = worksAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_IMG1
     *
     * @return the value of startup_works.WORKS_IMG1
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksImg1() {
        return worksImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_IMG1
     *
     * @param worksImg1 the value for startup_works.WORKS_IMG1
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksImg1(String worksImg1) {
        this.worksImg1 = worksImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_IMG2
     *
     * @return the value of startup_works.WORKS_IMG2
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksImg2() {
        return worksImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_IMG2
     *
     * @param worksImg2 the value for startup_works.WORKS_IMG2
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksImg2(String worksImg2) {
        this.worksImg2 = worksImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_IMG3
     *
     * @return the value of startup_works.WORKS_IMG3
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksImg3() {
        return worksImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_IMG3
     *
     * @param worksImg3 the value for startup_works.WORKS_IMG3
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksImg3(String worksImg3) {
        this.worksImg3 = worksImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_IMG4
     *
     * @return the value of startup_works.WORKS_IMG4
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksImg4() {
        return worksImg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_IMG4
     *
     * @param worksImg4 the value for startup_works.WORKS_IMG4
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksImg4(String worksImg4) {
        this.worksImg4 = worksImg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_IMG5
     *
     * @return the value of startup_works.WORKS_IMG5
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksImg5() {
        return worksImg5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_IMG5
     *
     * @param worksImg5 the value for startup_works.WORKS_IMG5
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksImg5(String worksImg5) {
        this.worksImg5 = worksImg5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column startup_works.WORKS_CONTENT
     *
     * @return the value of startup_works.WORKS_CONTENT
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public String getWorksContent() {
        return worksContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column startup_works.WORKS_CONTENT
     *
     * @param worksContent the value for startup_works.WORKS_CONTENT
     *
     * @mbggenerated Tue May 10 17:08:56 CST 2016
     */
    public void setWorksContent(String worksContent) {
        this.worksContent = worksContent;
    }
}